name: CI
on: [pull_request]
jobs:
  lint:
    name: GraphQL Inspector Validate
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: GraphQL Inspector
        uses: nutstick/graphql-inspector-action@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          check_name: GraphQL Inspector Validate
