name: Pull Request
on: [pull_request]
jobs:
  lint:
    name: GraphQL Inspector Validate
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@v1.25.0
